### ISSUE TITLE
Empty value at the text box result in exception

### ISSUE THREAD

**Issue by ajeebkp23** [MarkWithall/worlds-simplest-csharp-wpf-mvvm-example#1]
I am a beginner in WPF. So I coded the entire blog article at my own will. Then I found it is leading to an exception when input box is empty. Here is my code, on which I fixed the error. https://github.com/ajeebkp23/Simplest-WPF-MVVM-Example. Since, I didn't forked your code I am not coming with a PR.

**Comment by MarkWithall** [comment]
Indeed it does. Well spotted. I'm surprised that no one else has noticed this before. Thanks for letting me know. 

The question is now, is it better for:
- the `TextConverter` `convertion` [sic] parameter (which is spelled wrong in the example) to handle `null` in the model;
- or, `SomeText` in `Presenter` to not allow `null` in the viewmodel (by initialising it to an empty string)
- or, `ConvertText` to do nothing if `SomeText` is `null` (and possibly empty string too) - and maybe pop up a message box informing the user

This would be a much tidier fix in C# 6.0; I must create a branch with a C# 6.0 version of the code.
