### ISSUE TITLE
Link Problems

### ISSUE THREAD

**Issue by cpMDV** [MarkWithall/worlds-simplest-csharp-wpf-mvvm-example#17]
Hi Mark,

first of all thanks for the examples.

I landed here following your blog https://www.markwithall.com/programming/2013/03/01/worlds-simplest-csharp-wpf-mvvm-example.html

I have notized a couple of problems with links in your blog and here. They not a big deal, but I wanted to let you know, just in case you want to correct them.
1) The microsoft link posted in your blog when you talk about the possible memory leaks of theViewModel is not valid (MS has changed a lot of things and broken a big amount of links out there in the net)
2) The link to the c# 4.0 here in the readme.md is actually pointing the c# 6.0 branch (one can eassily change the url in the navigation bar to get there though)
3) The section "me on the web" of your blog could be reduced a bit since some of those links / services (specially Google's) don't exit anymore

P.S. 
Sorry that I posted it here as an issue, it's is the easiest way I found to contact you. 
If you want I can delete it later, because it actually has nothing to do with your code.

**Comment by MarkWithall** [comment]
Thanks for letting me know. It's hard to keep track of all these things, so being told of them is always welcome.

**Comment by cpMDV** [comment]
You are welcome.

I will just close the issue (I am new to GitHub and don't know if it is possible to delete it, as it is not really related to the code)

**Comment by MarkWithall** [comment]
I've fixed all of those issues now. Thanks again for reporting.

In general, GitHub issues are the right place to report any form of issue (not just code). Or even just to ask questions that you have about a repository.
